version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    versioning-strategy: "increase"
    reviewers:
      - "ackwell"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Australia/Sydney"
    # Only explicitly notify about major updates.
    ignore:
      - dependency-name: "*"
        update-types:
          # Rust _loves_ it's 0.x.y versions - is this going to block those?
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    # Group all version updates into a single pr.
    groups:
      dependencies:
        applies-to: "version-updates"
        patterns: ["*"]
