[workspace]
members = ["crates/*"]
# TODO: Update to 3 when targeting 1.84+ (probably 1.85 with new edition)
resolver = "2"

[workspace.package]
edition = "2021"
# NOTE: See /rust-toolchain.toml when updating.
rust-version = "1.82"
license = "AGPL-3.0-or-later"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
