[build]
rustflags = ["--cfg", "tokio_unstable"]

[env]
# Tables in our dataset like CharaMakeType have more columns than are supported by sqlite by default.
LIBSQLITE3_FLAGS = { value = "-DSQLITE_MAX_COLUMN=5000", force = true }

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
